<?php

$awards = array("Best in Show",
                "Best Opp. Age",
                "Best Self",
                "Best Tan",
                "Best Marked",
                "Best Satin",
                "Best AOV",
                "Best Juvenile",);


$breeds = array(				"Abyssinian",
								"Agouti Satin",
								"Agouti Tan",
								"Agouti",
								"American Brindle",
								"Argente Creme",
								"Argente",
								"Astrex",
								"Banded",
								"Black Tan",
								"Black",
								"Blue Burmese",
								"Blue Tan",
								"Blue",
								"Bluepoint Siamese",
								"Brindle",
								"Broken Marked",
								"Champagne Tan",
								"Champagne",
								"Chinchilla",
								"Chocolate Tan",
								"Chocolate",
								"Cinnamon Satin",
								"Cinnamon Tan",
								"Cinnamon",
								"Cream Satin",
								"Cream",
								"Dove Tan",
								"Dove",
								"Dutch",
								"Even Marked",
								"Fawn Satin",
								"Fawn",
								"Hereford",
								"Himalayan",
								"Ivory Satin",
								"Lilac",
								"Longhaired",
								"Marten Sable",
								"Merle",
								"Pearl",
								"Red Satin",
								"Red",
								"Rumpwhite",
								"Sable",
								"Seal Point Siamese Satin",
								"Seal Point Siamese",
								"Silver Agouti Satin",
								"Silver Agouti",
								"Silver Fox",
								"Silver Grey Tan",
								"Silver Tan",
								"Silver",
								"Silvered",
								"Splashed",
								"Tricolour",
								"Variegated",
								"White (Black Eye)",
								"White (Pink Eye)",);



$selfs= array(					"Black",
                			    "Blue",
                				"Champagne",
               				 	"Chocolate",
                				"Cream",
                				"Dove",
                				"Fawn",
                				"Lilac",
                				"Red",
                				"Silver",
								"White (Pink Eye)",
                                "White (Black Eye)",);

$tans= array(					"Agouti Tan",
								"Black Tan",
								"Blue Tan",
								"Champagne Tan",
								"Chocolate Tan",
								"Cinnamon Tan",
								"Dove Tan",
								"Silver Grey Tan",
								"Silver Tan",);

$marked= array(					"Banded",
								"Broken Marked",
								"Dutch",
								"Even Marked",
								"Hereford",
								"Rumpwhite",
								"Tricolour",
								"Variegated",);
                                
$satins=array(					"Agouti Satin",
								"Champagne Satin",
								"Cinnamon Satin",
								"Cream Satin",
								"Fawn Satin",
								"Ivory Satin",
               		 			"Red Satin",
                				"Seal Point Siamese Satin",
								"Silver Agouti Satin",
								"Silver Satin",);
                                

$aovs= array(					"Agouti",
								"Argente Creme",
								"Argente",
								"Astrex",
								"Black Fox",
								"Blue Fox",
								"Bluepoint Siamese",
								"Brindle",
								"Chinchilla",
								"Cinnamon",
								"Chocolate Fox",
								"Himalayan",
								"Lilac Fox",
								"Longhaired",
								"Marten Sable",
								"Pearl",
								"Sable",
								"Seal Point Siamese",
								"Silver Agouti",
								"Silvered",
								"Splashed",);

$age = array("Ad", "U8");

$points = array("1","2","3","4","5");



 ?>